buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }
        maven {
            name = "sponge"
            url = "https://repo.spongepowered.org/maven/"
        }
    }
    dependencies {
        // Forge 1.8.9 官方插件，与 Gradle 4.4.1 完美兼容
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

version = "1.0.0"
group = "client.m1ck3y.rattix"
archivesBaseName = "Rattix"

sourceCompatibility = targetCompatibility = '1.8'
compileJava.options.encoding = 'UTF-8'

compileJava {
    File mcpSrg = file("${System.getProperty('user.home')}/.gradle/caches/minecraft/de/oceanlabs/mcp/mcp_stable/22/srgs/mcp-srg.srg")
    File notchSrg = file("${System.getProperty('user.home')}/.gradle/caches/minecraft/de/oceanlabs/mcp/mcp_stable/22/srgs/mcp-notch.srg")
    options.compilerArgs += [
        "-AreobfSrgFile=${mcpSrg.canonicalPath}",
        "-AreobfNotchSrgFile=${notchSrg.canonicalPath}",
        "-AoutRefMapFile=${buildDir}/resources/main/mixins.rattix.refmap.json",
        "-AdefaultObfuscationEnv=searge"
    ]
}

repositories {
    mavenCentral()
    maven {
        name = "sponge"
        url = "https://repo.spongepowered.org/maven/"
    }
}

minecraft {
    version = "1.8.9-11.15.1.2318-1.8.9"
    runDir = "run"
    mappings = "stable_22"
    makeObfSourceJar = false
    clientJvmArgs = [
        "-Dforge.forceNoStencil=true",
        "-Dfml.coreMods.load=client.m1ck3y.rattix.injection.RattixLoadingPlugin"
    ]
    clientRunArgs = [
        "--tweakClass", "org.spongepowered.asm.launch.MixinTweaker",
        "--mixin", "mixins.rattix.json"
    ]
}

dependencies {
    compile('org.spongepowered:mixin:0.7.11-SNAPSHOT') {
        exclude module: 'launchwrapper'
        exclude module: 'guava'
        exclude module: 'gson'
        exclude module: 'commons-io'
    }
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': project.minecraft.version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    from {
        configurations.compile.filter { it.name.contains("mixin") }.collect {
            zipTree(it)
        }
    } {
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }

    exclude "META-INF/*.SF"
    exclude "META-INF/*.DSA"
    exclude "META-INF/*.RSA"

    manifest {
        attributes([
            "Specification-Title": "rattix",
            "Specification-Vendor": "rattix",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": project.version,
            "Implementation-Vendor": "rattix",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            "FMLCorePlugin": "client.m1ck3y.rattix.injection.RattixLoadingPlugin",
            "FMLCorePluginContainsFMLMod": "true",
            "ForceLoadAsMod": "true",
            "MixinConfigs": "mixins.rattix.json"
        ])
    }
}
