package client.m1ck3y.rattix;

import client.m1ck3y.rattix.module.ModuleManager;
import client.m1ck3y.rattix.module.clickgui.ClickGuiScreen;
import client.m1ck3y.rattix.util.FileManager;
import client.m1ck3y.rattix.util.FontUtil;
import net.minecraft.client.Minecraft;
import net.minecraft.client.settings.KeyBinding;
import net.minecraftforge.client.event.RenderGameOverlayEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.client.registry.ClientRegistry;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.gameevent.InputEvent;
import net.minecraftforge.fml.common.gameevent.TickEvent;
import org.lwjgl.input.Keyboard;
import org.lwjgl.opengl.Display;

import java.util.Collections;

@Mod(
    modid = RattixMod.MODID,
    name = RattixMod.NAME,
    version = RattixMod.VERSION,
    acceptedMinecraftVersions = "[1.8.9]",
    clientSideOnly = true
)
public class RattixMod {
    public static final String MODID = "rattix";
    public static final String NAME = "Rattix";
    public static final String VERSION = "1.0.0";

    @Mod.Instance(MODID)
    public static RattixMod instance;

    private ModuleManager moduleManager;
    private KeyBinding clickGuiKey;
    private boolean rshiftPressed = false;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        ModMetadata meta = event.getModMetadata();
        meta.autogenerated = false;
        meta.modId = MODID;
        meta.name = NAME;
        meta.version = VERSION;
        meta.description = "Rattix Client - A sleek and powerful CloudClient-style Forge 1.8.9 Mod.";
        meta.authorList = Collections.singletonList("Rattix Team");
        meta.credits = "Built with Minecraft Forge 1.8.9";
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {
        FileManager.init();
        FontUtil.init();
        moduleManager = new ModuleManager();

        // 注册按键绑定
        clickGuiKey = new KeyBinding("key.rattix.clickgui", Keyboard.KEY_RSHIFT, "key.categories.rattix");
        ClientRegistry.registerKeyBinding(clickGuiKey);

        // 注册到所有可能的 Forge/FML 事件总线，确保百分之百接收事件
        MinecraftForge.EVENT_BUS.register(this);
        FMLCommonHandler.instance().bus().register(this);

        Display.setTitle(NAME);
    }

    @SubscribeEvent
    public void onKeyInput(InputEvent.KeyInputEvent event) {
        if (Keyboard.getEventKeyState()) {
            int key = Keyboard.getEventKey();
            if (clickGuiKey != null && clickGuiKey.isPressed() || key == Keyboard.KEY_RSHIFT) {
                openClickGui();
            } else if (moduleManager != null) {
                moduleManager.onKey(key);
            }
        }
    }

    @SubscribeEvent
    public void onClientTick(TickEvent.ClientTickEvent event) {
        if (event.phase == TickEvent.Phase.END) {
            if (!NAME.equals(Display.getTitle())) {
                Display.setTitle(NAME);
            }
            if (moduleManager != null) {
                moduleManager.onTick();
            }
            FontUtil.ensureGlobalFontRenderer();

            // 直接轮询键盘状态，保证无论在任何状态下都能检测到右 Shift
            Minecraft mc = Minecraft.getMinecraft();
            if (mc.theWorld != null && mc.thePlayer != null) {
                boolean isDown = Keyboard.isKeyDown(Keyboard.KEY_RSHIFT);
                if (isDown && !rshiftPressed) {
                    if (mc.currentScreen == null) {
                        openClickGui();
                    }
                }
                rshiftPressed = isDown;
            }
        }
    }

    private void openClickGui() {
        Minecraft.getMinecraft().displayGuiScreen(new ClickGuiScreen());
    }

    @SubscribeEvent
    public void onRenderOverlay(RenderGameOverlayEvent.Post event) {
        if (event.type == RenderGameOverlayEvent.ElementType.TEXT) {
            Minecraft mc = Minecraft.getMinecraft();
            if (moduleManager != null && mc.thePlayer != null && !mc.gameSettings.showDebugInfo) {
                moduleManager.onRender2D();
            }
        }
    }

    public ModuleManager getModuleManager() {
        return moduleManager;
    }
}
