package client.m1ck3y.rattix;

import client.m1ck3y.rattix.command.CommandManager;
import client.m1ck3y.rattix.config.ConfigManager;
import client.m1ck3y.rattix.event.EventManager;
import client.m1ck3y.rattix.event.events.KeyEvent;
import client.m1ck3y.rattix.event.events.Render2DEvent;
import client.m1ck3y.rattix.event.events.TickEvent;
import client.m1ck3y.rattix.modules.ClickGUI;
import client.m1ck3y.rattix.modules.manager.Register;
import client.m1ck3y.rattix.script.ScriptManager;
import client.m1ck3y.rattix.utils.FileManager;
import client.m1ck3y.rattix.utils.FontUtil;
import client.m1ck3y.rattix.utils.IconUtils;
import client.m1ck3y.rattix.utils.StartupScreen;
import net.minecraft.client.Minecraft;
import net.minecraft.client.settings.KeyBinding;
import net.minecraftforge.client.event.RenderGameOverlayEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.client.registry.ClientRegistry;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.gameevent.InputEvent;
import org.lwjgl.input.Keyboard;
import org.lwjgl.opengl.Display;

import java.util.Collections;

@Mod(
    modid = RattixMod.MODID,
    name = RattixMod.NAME,
    version = RattixMod.VERSION,
    acceptedMinecraftVersions = "[1.8.9]",
    clientSideOnly = true
)
public class RattixMod {
    public static final String MODID = "rattix";
    public static final String NAME = "Rattix";
    public static final String VERSION = "1.0.0";

    @Mod.Instance(MODID)
    public static RattixMod instance;

    private KeyBinding clickGuiKey;
    private boolean rshiftPressed;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        StartupScreen.setupSplashProgress();
        StartupScreen.stopForgeSplash();

        ModMetadata meta = event.getModMetadata();
        meta.autogenerated = false;
        meta.modId = MODID;
        meta.name = NAME;
        meta.version = VERSION;
        meta.description = "Rattix Client - A sleek and powerful CloudClient-style Forge 1.8.9 Mod.";
        meta.authorList = Collections.singletonList("Rattix Team");
        meta.credits = "Built with Minecraft Forge 1.8.9";

        updateTitleAndIcon();
        StartupScreen.draw("Starting Rattix Client...", 0.15f);
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {
        StartupScreen.draw("Initializing File Manager & Fonts...", 0.30f);
        FileManager.init();
        FontUtil.init();

        StartupScreen.draw("Loading Configurations...", 0.50f);
        ConfigManager.getInstance().init();

        StartupScreen.draw("Loading Scripts...", 0.70f);
        ScriptManager.getInstance().init();

        StartupScreen.draw("Registering Modules & Categories...", 0.90f);
        Register.registerAll();

        clickGuiKey = new KeyBinding("key.rattix.clickgui", Keyboard.KEY_RSHIFT, "key.categories.rattix");
        ClientRegistry.registerKeyBinding(clickGuiKey);

        // 注册到所有可能的 Forge/FML 事件总线，确保百分之百接收事件
        MinecraftForge.EVENT_BUS.register(this);
        FMLCommonHandler.instance().bus().register(this);

        updateTitleAndIcon();
        StartupScreen.draw("Rattix Client Ready", 1.0f);
        StartupScreen.installLoadingScreen();
    }

    public static void updateTitleAndIcon() {
        try {
            if (Display.isCreated()) {
                Display.setTitle(NAME);
                IconUtils.initLwjglIcon();
            }
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }

    public static void setWindowIcon() {
        IconUtils.initLwjglIcon();
    }

    @SubscribeEvent
    public void onKeyInput(InputEvent.KeyInputEvent event) {
        if (Keyboard.getEventKeyState()) {
            int key = Keyboard.getEventKey();
            if (key == 0) {
                key = Keyboard.getEventCharacter() + 256;
            }
            EventManager.getInstance().call(new KeyEvent(key));

            Register clickGui = Register.getModule(client.m1ck3y.rattix.modules.ClickGUI.class);
            int guiKey = (clickGui != null && clickGui.getKeyCode() != 0) ? clickGui.getKeyCode() : Keyboard.KEY_RSHIFT;

            if ((this.clickGuiKey != null && this.clickGuiKey.isPressed()) || key == Keyboard.KEY_RSHIFT || key == guiKey) {
                openClickGui();
            } else {
                Register.onKey(key);
            }
        }
    }

    @SubscribeEvent
    public void onClientTick(net.minecraftforge.fml.common.gameevent.TickEvent.ClientTickEvent event) {
        if (event.phase == net.minecraftforge.fml.common.gameevent.TickEvent.Phase.END) {
            EventManager.getInstance().call(new TickEvent());
            if (!NAME.equals(Display.getTitle())) {
                Display.setTitle(NAME);
            }
            Register.onClientTick();
            FontUtil.ensureGlobalFontRenderer();

            Minecraft mc = Minecraft.getMinecraft();
            if (mc.theWorld != null && mc.thePlayer != null) {
                boolean isDown = Keyboard.isKeyDown(Keyboard.KEY_RSHIFT);
                if (isDown && !this.rshiftPressed && mc.currentScreen == null) {
                    openClickGui();
                }
                this.rshiftPressed = isDown;
            }
        }
    }

    public static void openClickGui() {
        ClickGUI.open();
    }

    @SubscribeEvent
    public void onRenderOverlay(RenderGameOverlayEvent.Post event) {
        if (event.type == RenderGameOverlayEvent.ElementType.TEXT) {
            EventManager.getInstance().call(new Render2DEvent(event.partialTicks));
            Minecraft mc = Minecraft.getMinecraft();
            if (mc.thePlayer != null && !mc.gameSettings.showDebugInfo) {
                Register.onRenderOverlay();
            }
        }
    }

    @SubscribeEvent
    public void onGuiOpen(net.minecraftforge.client.event.GuiOpenEvent event) {
        StartupScreen.installLoadingScreen();
    }

    public CommandManager getCommandManager() {
        return CommandManager.getInstance();
    }

    public EventManager getEventManager() {
        return EventManager.getInstance();
    }
}
